# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml
analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
linter:
  rules:
    top_level_function_literal_block: false